# This is a Powershell script which gets `projectId` from `appsettings.json` and is responsible for generating strongly typed models from Kontent CMS.
# Generated models are stored in the `Models` directory.
# Models are generated by Kontent Generator https://github.com/Kentico/kontent-generators-net tool. 
dotnet tool restore
$OUTPUT_PATH = Join-Path $PSScriptRoot ".\Models\ContentTypes"
$appSettings = Get-Content '.\appsettings.json' | Out-String | ConvertFrom-Json
dotnet tool run KontentModelGenerator -p $appSettings."DeliveryOptions"."ProjectId" -o $OUTPUT_PATH -n "StatiqTutorial"